version: "3"
services:
  frontend:
    build: ./apps/web
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  backend:
    build: ./apps/server
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
