services:
  - type: web
    name: your-service-name
    buildCommand: |
      apt-get update
      apt-get install -y tesseract-ocr
      pip install -r requirements.txt
    startCommand: gunicorn document_server.wsgi
